fix

diff --git a/cdk-jenkins/codebuild_stack/codebuild_behave_scanning_buildspec.yaml b/cdk-jenkins/codebuild_stack/codebuild_behave_scanning_buildspec.yaml
--- a/cdk-jenkins/codebuild_stack/codebuild_behave_scanning_buildspec.yaml
+++ b/cdk-jenkins/codebuild_stack/codebuild_behave_scanning_buildspec.yaml
@@ -23,9 +23,18 @@ phases:
           -e PYTHONPATH=/app/behave/libs \
           -v $(pwd):/app \
           $ECR_URL:latest \
-          behave /app/behave/features | tee output.txt
+          behave /app/behave/features ; echo $? > output.txt
+      - echo "docker result $?"
       - echo "Command output:"
       - cat output.txt
   post_build:
     commands:
       - echo Build completed on `date`
+      - BUILD_STATUS=$(cat output.txt)
+      - |
+        if [ "$BUILD_STATUS" -ne "0" ]; then
+          echo "Build failed with status code $BUILD_STATUS"
+          exit 1
+        else
+          echo "Build succeeded with status code $BUILD_STATUS"
+        fi
